name: dos
description: An app to help you log your emotions.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.0
  path: ^1.6.4
  path_provider: ^1.6.7
  intl: ^0.16.1
  flutter_chips_input: ^1.8.1
  flutter_sound_lite: ^4.0.0
  uuid: ^2.0.4
  material_design_icons_flutter: ^4.0.5345
  charts_flutter: ^0.9.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.5"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# Run `flutter pub run flutter_launcher_icons:main` to regen icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/dos.png"
  adaptive_icon_background: "#FFB699"
  adaptive_icon_foreground: "assets/icons/android.png"